---
- hosts: localhost
  name: Deploy a 2-node ONTAP Simulator HA Pair (experimental)
  gather_facts: false
  vars:
    vcenter_address: "vcenter-01v.pharmax.local"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "P@ssw0rd"
    vcenter_datacenter: "PHARMAX-VSI-DC"
    vcenter_cluster: "RegionHQ-MGMT"
  tasks:
    # In this scenario the partner node is deployed automatically
    - include_role:
        name: deploy_ovf_vsim
      vars:
        force: true
        vm_name: "cluster-asa-01"
        partner_name: "cluster-asa-02"
        vm_datastore: "SSD-HIGH-PERF"
        data_network: "VMWARE-LAB"
        cluster_network: "GOAD-LAN"
        ontap_cluster_name: "PHARMAX-ASA"
        ontap_cluster_mgmt_ip: "192.168.5.60"
        sys_serial_number: "4082368511"
        partner_serial: "4034389062"
        ontap_node_mgmt_ip: "192.168.5.61"
        partner_ip: "192.168.5.62"
        ontap_netmask: "255.255.255.0"
        ontap_gateway: "192.168.5.254"
        ontap_dns_domain: "pharmax.local"
        ontap_dns_server: "192.168.5.1"
        disk_model: "vscsi"
        shelf0_disk_count: 12
        shelf0_disk_size: 4096
        shelf1_disk_count: 12
        shelf1_disk_size: 4096
        adpv2_enabled: true
        shelf_disk_provisioning: "eagerzeroedthick"
        ontap_password: "P@ssw0rd"
        fake_ssd_disk_size: 4096
        serial_ports:
          - type: "network"
            service_uri: "telnet://192.168.5.253:{{serial_tcp_port_node1}}"
            direction: "server"
            yield_on_poll: true
        partner_serial_ports:
          - type: "network"
            service_uri: "telnet://192.168.5.253:{{serial_tcp_port_node2}}"
            direction: "server"
            yield_on_poll: true
        serial_tcp_port_node1: 1029
        serial_tcp_port_node2: 1030
        bootargs:
          [
            "bootarg.init.auto_cluster_lif.disable false",
            "console comconsole,vidconsole",
            "comconsole_speed 115200",
            "root-uses-shared-disks? true",
            "root-uses-shared-ssds? true",
            "allow-flash-optimized? true",
            "bootarg.init.flash_optimized true",
            "bootarg.vm.no_poweroff_on_halt false",
            "bootarg.template.bootmenu.cluster_uuid eb931894-50d0-4153-beda-e069414aaadd",
            "bootarg.init.san_optimized true",
          ]
